# Logica difusa

## Conjuntos clásicos

In [2]:
A = {0, 2, 4, 5, 8}
B = {1, 2, 3, 4, 5}

In [3]:
# Unión
A | B

{0, 1, 2, 3, 4, 5, 8}

In [4]:
# Intersección
A & B

{2, 4, 5}

In [5]:
# Diferencia
A - B

{0, 8}

## Conjuntos difusos
### Función de membresia

El siguiente ejemplo representa el problema de definir la propina en un restaurant. Para determinar la propina se utiliza la calidad del servicio evaluado en un rango del 0 al 10. Este ejemplo solo muestra una parte del problema para determinar la calidad del servicio.

In [1]:
# scikit-fuzzy
import numpy as np
import skfuzzy as sk

In [2]:
#Arreglo numpy con la calidad de una propina
x_qual = np.arange(0, 11, 1)

In [3]:
# Arreglo numpy para una función de membresía triangular trimf
qual_lo = sk.trimf(x_qual, [0, 0, 5])

In [5]:
# Arreglo numpy para una función de membresía trapezoidal trapmf
qual_lo = sk.trapmf(x_qual, [0, 0, 5, 5])

In [6]:
# Arreglo numpy para una función de membresía gaussiana gaussmf
qual_lo = sk.gaussmf(x_qual, np.mean(x_qual), np.std(x_qual))

In [ ]:
# Arreglo numpy para una función de membresía campana bellmf
qual_lo = sk.bellmf(x_qual, 0.5, 0.5, 0.5)

In [7]:
# Arreglo numpy para una función de membresía sigmoide sigmf
qual_lo = sk.sigmf(x_qual, 0.5, 0.5)

In [9]:
# Arreglo numpy para una función de membresía triangular
qual_lo = sk.trimf(x_qual, [0, 0, 5])
qual_md = sk.trimf(x_qual, [0, 5, 10])


In [10]:

# Encontrar el maximo (Fuzzy or)
sk.fuzzy_or(x_qual, qual_lo, x_qual, qual_md )

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([1. , 0.8, 0.6, 0.6, 0.8, 1. , 0.8, 0.6, 0.4, 0.2, 0. ]))

In [12]:
# Encontrar el mínimo (Fuzzy and)
sk.fuzzy_and(x_qual, qual_lo, x_qual, qual_md )

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([0. , 0.2, 0.4, 0.4, 0.2, 0. , 0. , 0. , 0. , 0. , 0. ]))

In [13]:
#Encontrar el complemento (Fuzzy not)
sk.fuzzy_not(qual_lo)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1. , 1. , 1. , 1. , 1. ])

In [14]:
#Encontrar el producto (Fuzzy Cartesiano)
sk.cartprod(qual_lo, qual_md)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 0.8, 0.8, 0.6, 0.4, 0.2, 0. ],
       [0. , 0.2, 0.4, 0.6, 0.6, 0.6, 0.6, 0.6, 0.4, 0.2, 0. ],
       [0. , 0.2, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.2, 0. ],
       [0. , 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

In [15]:
# Encontrar la diferencia (Diferencia difusa)
sk.fuzzy_sub(x_qual, qual_lo, x_qual, qual_md)

(array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
          1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]),
 array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 0.8, 0.8, 0.6, 0.6, 0.4, 0.4, 0.2,
        0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. ]))