# Ejemplo Adaline

En este ejemplo utilizaremos la compuerta lógica **AND** para entrenar Adaline

| No. |Entradas  |  Salidas  |
|-----|----------|-----------|
|1    |( 1,   1) |    1      |
|2    |( 1,   0) |    0      |
|3    |( 0,   1) |    0      |
|4    |( 0,   0) |    0      |

## Iteración 1: Paso 0. Inicialización de pesos

La inicialización de pesos del Adaline puede ser aleatoria, con número pequeños entre [0, 1] o asignado a todos los pesos el valor inicial de cero.

In [1]:
w = [-0.6, 0.3, 0.2]

## Iteración 1

Se utilizan toda la muestra de entrenamiento

In [2]:
X = [[0, 0], [1, 0], [0, 1], [1, 1]]
t = [0, 0, 0, 1]

Para calcular salida actual de Adaline utilizamos:
$\hat y = \sum w_ix_i + w_bb$

In [3]:
import numpy as np

# entrada a la red
y_input = np.dot(X, w[1:]) + w[0]
print (y_input)


[-0.6 -0.3 -0.4 -0.1]


In [4]:
# activación identidad

In [5]:
# errores
errors = t - y_input
print (errors)

[0.6 0.3 0.4 1.1]


In [6]:
# ajuste de pesos
eta = 0.5
w[1:] += eta * np.dot(np.transpose(X), errors)
w[0] += eta * np.sum(errors)
print(w)

[0.6, 1.0, 0.95]


# Iteración 2

In [8]:
# entrada a la red
y_input = np.dot(X, w[1:]) + w[0]
print('Entradas a la neurona:')
print (y_input)

# activación identidad

# errores
errors = t - y_input
print('Errores de cada ejemplo de entrenamiento.')
print (errors)

# ajuste de pesos
eta = 0.5
w[1:] += eta * np.dot(np.transpose(X), errors)
w[0] += eta * np.sum(errors)
print('Nuevos pesos')
print(w)

[0.6  1.6  1.55 2.55]
[-0.6  -1.6  -1.55 -1.55]
[-2.05, -0.575, -0.5999999999999999]


# Iteración 3

In [10]:
# entrada a la red
y_input = np.dot(X, w[1:]) + w[0]
print('Entradas a la neurona:')
print (y_input)

# activación identidad

# errores
errors = t - y_input
print('Errores de cada ejemplo de entrenamiento.')
print (errors)

# ajuste de pesos
eta = 0.5
w[1:] += eta * np.dot(np.transpose(X), errors)
w[0] += eta * np.sum(errors)
print('Nuevos pesos')
print(w)

Entradas a la neurona:
[-2.05  -2.625 -2.65  -3.225]
Errores de cada ejemplo de entrenamiento.
[2.05  2.625 2.65  4.225]
Nuevos pesos
[3.7249999999999996, 2.8499999999999996, 2.8374999999999995]
